name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [ linux, windows, macos ]
        
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/fif
            asset_name: fif-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/fif.exe
            asset_name: fif-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/fif
            asset_name: fif-macos

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose --all-features
    - name: Build
      run: cargo build --release --verbose --all-features
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}
